import { NextRequest, NextResponse } from "next/server";
import { validateSession } from "@/lib/server/auth/session";
import { checkRateLimit } from "@/lib/server/auth/rate-limit";
import { requestIp } from "@/lib/server/auth/ip";
import { createSavedAnalysis, listSavedAnalyses } from "@/lib/server/phase2/repositories";
import { normalizeIdempotencyKey, normalizeMintAddress, pageParams } from "@/lib/server/phase2/validation";
const noStore = { "Cache-Control": "no-store" };
export async function GET(request: NextRequest) { const session = await validateSession(request); if (!session) return NextResponse.json({ error:"Unauthenticated" }, { status:401, headers:noStore }); const { from, to, page, limit } = pageParams(request.nextUrl.searchParams); try { const data = await listSavedAnalyses(session.userId, from, to); return NextResponse.json({ success:true, data:data.rows, pagination:{ page, limit, total:data.count } }, { headers:noStore }); } catch { return NextResponse.json({ error:"Unable to load analyses" }, { status:500, headers:noStore }); } }
export async function POST(request: NextRequest) { const session = await validateSession(request); if (!session) return NextResponse.json({ error:"Unauthenticated" }, { status:401, headers:noStore }); const limited = await checkRateLimit("save_analysis", [requestIp(request), session.userId]); if (!limited.allowed) return NextResponse.json({ error:"Too many requests" }, { status:429, headers:{ ...noStore, "Retry-After": String(limited.retryAfter) } }); let body: unknown; try { body = await request.json(); } catch { return NextResponse.json({ error:"Malformed request" }, { status:400, headers:noStore }); } const parsedBody = body as { mintAddress?: unknown; idempotencyKey?: unknown }; const mint = normalizeMintAddress(parsedBody?.mintAddress); if (!mint) return NextResponse.json({ error:"Invalid mint address" }, { status:400, headers:noStore }); const idempotencyKey = normalizeIdempotencyKey(parsedBody?.idempotencyKey); if (parsedBody?.idempotencyKey !== undefined && !idempotencyKey) return NextResponse.json({ error:"Invalid idempotency key" }, { status:400, headers:noStore }); try { const saved = await createSavedAnalysis(session.userId, mint, idempotencyKey); if (!saved) return NextResponse.json({ error:"No verified report exists for this token" }, { status:404, headers:noStore }); return NextResponse.json({ success:true, data:saved }, { status:201, headers:noStore }); } catch { return NextResponse.json({ error:"Unable to save analysis" }, { status:500, headers:noStore }); } }
