import "server-only";
import { supabaseAdmin } from "@/lib/server/supabase-admin";
import { normalizeMintAddress } from "./validation";
export type SavedAnalysis = { id:string; user_id:string; token_id:string|null; mint_address:string; risk_report_id:string|null; token_snapshot_id:string|null; risk_score:number|null; risk_level:string|null; confidence:number|null; reasons:unknown[]; ai_explanation:string|null; source_metadata:Record<string,unknown>; analyzed_at:string; created_at:string; tokens?: { name:string|null; symbol:string|null; logo_url:string|null } | null };
export type WatchlistItem = { id:string; user_id:string; token_id:string|null; mint_address:string; created_at:string; tokens?: { name:string|null; symbol:string|null; logo_url:string|null } | null };
type RiskRow = { id:string; token_id:string; overall_risk_score:number|null; overall_risk_label:string|null; confidence:number|null; risk_factors:unknown; ai_headline:string|null; ai_summary:string|null; ai_findings:string[]|null; ai_limitations:string[]|null; ai_provider:string|null; ai_model:string|null; ai_generated_at:string|null; generated_at:string|null; calculated_at:string|null };
function reasons(riskFactors: unknown, findings: unknown): unknown[] { if (Array.isArray(findings)) return findings.filter((x) => typeof x === "string"); if (riskFactors && typeof riskFactors === "object" && !Array.isArray(riskFactors)) { const value = (riskFactors as Record<string, unknown>).factors; return Array.isArray(value) ? value : []; } return []; }
function aiText(row: RiskRow) { const parts = [row.ai_headline, row.ai_summary, ...(Array.isArray(row.ai_findings) ? row.ai_findings : []), ...(Array.isArray(row.ai_limitations) ? row.ai_limitations : [])].filter((v): v is string => typeof v === "string" && v.length > 0); return parts.length ? parts.join("\n\n") : null; }
export async function loadCurrentReportSnapshot(mint: string) { const { data: token, error: tokenError } = await supabaseAdmin.from("tokens").select("id,mint_address,name,symbol,logo_url").eq("mint_address", mint).maybeSingle(); if (tokenError) throw new Error("token_lookup_failed"); if (!token) return null; const [riskResult, snapshotResult] = await Promise.all([supabaseAdmin.from("risk_reports").select("*").eq("token_id", token.id).order("generated_at", { ascending:false }).limit(1).maybeSingle(), supabaseAdmin.from("token_snapshots").select("id,source,snapshot_at").eq("token_id", token.id).order("snapshot_at", { ascending:false }).limit(1).maybeSingle()]); if (riskResult.error || snapshotResult.error) throw new Error("report_lookup_failed"); const risk = riskResult.data as RiskRow | null; if (!risk) return null; const snap = snapshotResult.data as { id:string; source:string|null; snapshot_at:string|null } | null; const analyzedAt = risk.ai_generated_at ?? risk.calculated_at ?? risk.generated_at ?? snap?.snapshot_at; if (!analyzedAt) return null; return { token, risk, row: { token_id: token.id, mint_address: mint, risk_report_id: risk.id, token_snapshot_id: snap?.id ?? null, risk_score: risk.overall_risk_score, risk_level: risk.overall_risk_label, confidence: risk.confidence, reasons: reasons(risk.risk_factors, risk.ai_findings), ai_explanation: aiText(risk), source_metadata: { risk_report_id: risk.id, token_snapshot_id: snap?.id ?? null, token_id: token.id, snapshot_source: snap?.source ?? null, ai_provider: risk.ai_provider, ai_model: risk.ai_model }, analyzed_at: analyzedAt } }; }
export async function createSavedAnalysis(userId:string, mint:string) { const snapshot = await loadCurrentReportSnapshot(mint); if (!snapshot) return null; const since = new Date(Date.now() - 10_000).toISOString(); const { data: existing } = await supabaseAdmin.from("saved_analyses").select("*").eq("user_id", userId).eq("mint_address", mint).eq("risk_report_id", snapshot.risk.id).gte("created_at", since).order("created_at", { ascending:false }).limit(1).maybeSingle(); if (existing) return existing as SavedAnalysis; const { data, error } = await supabaseAdmin.from("saved_analyses").insert({ user_id: userId, ...snapshot.row }).select("*").single(); if (error) throw new Error("saved_analysis_insert_failed"); return data as SavedAnalysis; }
export async function listSavedAnalyses(userId:string, from=0, to=19) { const { data, count, error } = await supabaseAdmin.from("saved_analyses").select("*,tokens(name,symbol,logo_url)", { count:"exact" }).eq("user_id", userId).order("created_at", { ascending:false }).order("id", { ascending:false }).range(from, to); if (error) throw new Error("saved_analysis_list_failed"); return { rows: (data ?? []) as SavedAnalysis[], count: count ?? 0 }; }
export async function getSavedAnalysis(userId:string, id:string) { const { data, error } = await supabaseAdmin.from("saved_analyses").select("*,tokens(name,symbol,logo_url)").eq("user_id", userId).eq("id", id).maybeSingle(); if (error) throw new Error("saved_analysis_get_failed"); return data as SavedAnalysis | null; }
export async function deleteSavedAnalysis(userId:string, id:string) { const { error } = await supabaseAdmin.from("saved_analyses").delete().eq("user_id", userId).eq("id", id); if (error) throw new Error("saved_analysis_delete_failed"); }
export async function listWatchlist(userId:string) { const { data, error } = await supabaseAdmin.from("watchlist_items").select("*,tokens(name,symbol,logo_url)").eq("user_id", userId).order("created_at", { ascending:false }).limit(50); if (error) throw new Error("watchlist_list_failed"); return (data ?? []) as WatchlistItem[]; }
export async function addWatchlistItem(userId:string, mint:string) { const { data: token, error: tokenError } = await supabaseAdmin.from("tokens").select("id").eq("mint_address", mint).maybeSingle(); if (tokenError) throw new Error("token_lookup_failed"); if (!token) return null; const { data, error } = await supabaseAdmin.from("watchlist_items").upsert({ user_id:userId, token_id: token.id, mint_address: mint }, { onConflict:"user_id,mint_address", ignoreDuplicates:false }).select("*").single(); if (error) throw new Error("watchlist_add_failed"); return data as WatchlistItem; }
export async function removeWatchlistItem(userId:string, rawMint:string) { const mint = normalizeMintAddress(rawMint); if (!mint) return false; const { error } = await supabaseAdmin.from("watchlist_items").delete().eq("user_id", userId).eq("mint_address", mint); if (error) throw new Error("watchlist_remove_failed"); return true; }
export async function getWatchlistMintSet(userId:string) { const rows = await listWatchlist(userId); return new Set(rows.map((r) => r.mint_address)); }
export async function getLatestRiskByTokenIds(tokenIds: string[]) { if (!tokenIds.length) return new Map<string, { score:number|null; level:string|null; confidence:number|null; generated_at:string|null }>(); const { data } = await supabaseAdmin.from("risk_reports").select("token_id,overall_risk_score,overall_risk_label,confidence,generated_at").in("token_id", tokenIds).order("generated_at", { ascending:false }); const map = new Map<string, { score:number|null; level:string|null; confidence:number|null; generated_at:string|null }>(); for (const row of data ?? []) if (!map.has(String(row.token_id))) map.set(String(row.token_id), { score: row.overall_risk_score, level: row.overall_risk_label, confidence: row.confidence, generated_at: row.generated_at }); return map; }
export async function getDashboardData(userId:string) { const [recent, watchlist, allFirstPage] = await Promise.all([listSavedAnalyses(userId, 0, 4), listWatchlist(userId), listSavedAnalyses(userId,0,49)]); const latestRisk = await getLatestRiskByTokenIds(watchlist.flatMap((w) => w.token_id ? [w.token_id] : [])); const distinctTokens = new Set(allFirstPage.rows.map((a) => a.mint_address)).size; return { analyses: recent.rows, watchlist: watchlist.slice(0,5), latestRisk, counts: { savedAnalyses: allFirstPage.count, watchlist: watchlist.length, tokensAnalyzed: distinctTokens, latestSavedAt: recent.rows[0]?.created_at ?? null } }; }
