function reasons(riskFactors, findings) { if (Array.isArray(findings)) return findings.filter((x) => typeof x === "string"); if (riskFactors && typeof riskFactors === "object" && !Array.isArray(riskFactors)) { const value = riskFactors.factors; return Array.isArray(value) ? value : []; } return []; }
function aiText(row) { const parts = [row.ai_headline, row.ai_summary, ...(Array.isArray(row.ai_findings) ? row.ai_findings : []), ...(Array.isArray(row.ai_limitations) ? row.ai_limitations : [])].filter((v) => typeof v === "string" && v.length > 0); return parts.length ? parts.join("\n\n") : null; }
export function createPhase2Repository(client, normalizeMintAddress, monitoring = null) {
  async function loadCurrentReportSnapshot(mint) { const { data: token, error: tokenError } = await client.from("tokens").select("id,mint_address,name,symbol,logo_url").eq("mint_address", mint).maybeSingle(); if (tokenError) throw new Error("token_lookup_failed"); if (!token) return null; const [riskResult, snapshotResult] = await Promise.all([client.from("risk_reports").select("*").eq("token_id", token.id).order("generated_at", { ascending:false }).limit(1).maybeSingle(), client.from("token_snapshots").select("id,source,snapshot_at").eq("token_id", token.id).order("snapshot_at", { ascending:false }).limit(1).maybeSingle()]); if (riskResult.error || snapshotResult.error) throw new Error("report_lookup_failed"); const risk = riskResult.data; if (!risk) return null; const snap = snapshotResult.data; const analyzedAt = risk.ai_generated_at ?? risk.calculated_at ?? risk.generated_at ?? snap?.snapshot_at; if (!analyzedAt) return null; return { token, risk, row: { token_id: token.id, mint_address: mint, risk_report_id: risk.id, token_snapshot_id: snap?.id ?? null, risk_score: risk.overall_risk_score, risk_level: risk.overall_risk_label, confidence: risk.confidence, reasons: reasons(risk.risk_factors, risk.ai_findings), ai_explanation: aiText(risk), source_metadata: { risk_report_id: risk.id, token_snapshot_id: snap?.id ?? null, token_id: token.id, snapshot_source: snap?.source ?? null, ai_provider: risk.ai_provider, ai_model: risk.ai_model }, analyzed_at: analyzedAt } }; }
  async function findByIdempotencyKey(userId, idempotencyKey) { const { data, error } = await client.from("saved_analyses").select("*").eq("user_id", userId).eq("idempotency_key", idempotencyKey).maybeSingle(); if (error) throw new Error("saved_analysis_idempotency_lookup_failed"); return data ?? null; }
  async function createSavedAnalysis(userId, mint, idempotencyKey = null) { if (idempotencyKey) { const existing = await findByIdempotencyKey(userId, idempotencyKey); if (existing) return existing; } const snapshot = await loadCurrentReportSnapshot(mint); if (!snapshot) return null; const { data, error } = await client.from("saved_analyses").insert({ user_id: userId, idempotency_key: idempotencyKey, ...snapshot.row }).select("*").single(); if (error) { if (idempotencyKey && error.code === "23505") { const existing = await findByIdempotencyKey(userId, idempotencyKey); if (existing) return existing; } throw new Error("saved_analysis_insert_failed"); } if (monitoring?.safeEnrollTrackedToken) await monitoring.safeEnrollTrackedToken({ tokenId: snapshot.token.id, mintAddress: mint, source: "saved_analysis" }); return data; }
  async function listSavedAnalyses(userId, from=0, to=19) { const { data, count, error } = await client.from("saved_analyses").select("*,tokens(name,symbol,logo_url)", { count:"exact" }).eq("user_id", userId).order("created_at", { ascending:false }).order("id", { ascending:false }).range(from, to); if (error) throw new Error("saved_analysis_list_failed"); return { rows: data ?? [], count: count ?? 0 }; }
  async function getSavedAnalysis(userId, id) { const { data, error } = await client.from("saved_analyses").select("*,tokens(name,symbol,logo_url)").eq("user_id", userId).eq("id", id).maybeSingle(); if (error) throw new Error("saved_analysis_get_failed"); return data ?? null; }
  async function deleteSavedAnalysis(userId, id) { const { error } = await client.from("saved_analyses").delete().eq("user_id", userId).eq("id", id); if (error) throw new Error("saved_analysis_delete_failed"); }
  async function listWatchlist(userId) { const { data, error } = await client.from("watchlist_items").select("*,tokens(name,symbol,logo_url)").eq("user_id", userId).order("created_at", { ascending:false }).limit(50); if (error) throw new Error("watchlist_list_failed"); return data ?? []; }
  async function addWatchlistItem(userId, mint) { const { data: token, error: tokenError } = await client.from("tokens").select("id").eq("mint_address", mint).maybeSingle(); if (tokenError) throw new Error("token_lookup_failed"); if (!token) return null; const { data, error } = await client.from("watchlist_items").upsert({ user_id:userId, token_id: token.id, mint_address: mint }, { onConflict:"user_id,mint_address", ignoreDuplicates:false }).select("*").single(); if (error) throw new Error("watchlist_add_failed"); if (monitoring?.safeEnrollTrackedToken) await monitoring.safeEnrollTrackedToken({ tokenId: token.id, mintAddress: mint, source: "watchlist" }); return data; }
  async function removeWatchlistItem(userId, rawMint) { const mint = normalizeMintAddress(rawMint); if (!mint) return false; const { error } = await client.from("watchlist_items").delete().eq("user_id", userId).eq("mint_address", mint); if (error) throw new Error("watchlist_remove_failed"); if (monitoring?.safeReconcileWatchlistTracking) await monitoring.safeReconcileWatchlistTracking(mint); return true; }
  async function getLatestRiskByTokenIds(tokenIds) { if (!tokenIds.length) return new Map(); const { data } = await client.from("risk_reports").select("token_id,overall_risk_score,overall_risk_label,confidence,generated_at").in("token_id", tokenIds).order("generated_at", { ascending:false }); const map = new Map(); for (const row of data ?? []) if (!map.has(String(row.token_id))) map.set(String(row.token_id), { score: row.overall_risk_score, level: row.overall_risk_label, confidence: row.confidence, generated_at: row.generated_at }); return map; }
  async function getDashboardData(userId) { const [recent, watchlist, allFirstPage] = await Promise.all([listSavedAnalyses(userId, 0, 4), listWatchlist(userId), listSavedAnalyses(userId,0,49)]); const latestRisk = await getLatestRiskByTokenIds(watchlist.flatMap((w) => w.token_id ? [w.token_id] : [])); const distinctTokens = new Set(allFirstPage.rows.map((a) => a.mint_address)).size; return { analyses: recent.rows, watchlist: watchlist.slice(0,5), latestRisk, counts: { savedAnalyses: allFirstPage.count, watchlist: watchlist.length, tokensAnalyzed: distinctTokens, latestSavedAt: recent.rows[0]?.created_at ?? null } }; }
  return { loadCurrentReportSnapshot, createSavedAnalysis, listSavedAnalyses, getSavedAnalysis, deleteSavedAnalysis, listWatchlist, addWatchlistItem, removeWatchlistItem, getLatestRiskByTokenIds, getDashboardData };
}
