import { NextRequest, NextResponse } from "next/server";
import { validateSession } from "@/lib/server/auth/session";
import { checkRateLimit } from "@/lib/server/auth/rate-limit";
import { requestIp } from "@/lib/server/auth/ip";
import { addWatchlistItem, listWatchlist } from "@/lib/server/phase2/repositories";
import { normalizeMintAddress } from "@/lib/server/phase2/validation";
const noStore = { "Cache-Control":"no-store" };
export async function GET(request:NextRequest) { const session = await validateSession(request); if (!session) return NextResponse.json({ error:"Unauthenticated" }, { status:401, headers:noStore }); try { return NextResponse.json({ success:true, data: await listWatchlist(session.userId) }, { headers:noStore }); } catch { return NextResponse.json({ error:"Unable to load watchlist" }, { status:500, headers:noStore }); } }
export async function POST(request:NextRequest) { const session = await validateSession(request); if (!session) return NextResponse.json({ error:"Unauthenticated" }, { status:401, headers:noStore }); const limited = await checkRateLimit("watchlist_mutation", [requestIp(request), session.userId]); if (!limited.allowed) return NextResponse.json({ error:"Too many requests" }, { status:429, headers:{ ...noStore, "Retry-After": String(limited.retryAfter) } }); let body: unknown; try { body = await request.json(); } catch { return NextResponse.json({ error:"Malformed request" }, { status:400, headers:noStore }); } const mint = normalizeMintAddress((body as { mintAddress?: unknown })?.mintAddress); if (!mint) return NextResponse.json({ error:"Invalid mint address" }, { status:400, headers:noStore }); try { const item = await addWatchlistItem(session.userId, mint); if (!item) return NextResponse.json({ error:"Token is not available in OwlScope data" }, { status:404, headers:noStore }); return NextResponse.json({ success:true, data:item }, { headers:noStore }); } catch { return NextResponse.json({ error:"Unable to add watchlist item" }, { status:500, headers:noStore }); } }
