import "server-only";

import { supabaseAdmin } from "@/lib/supabase-server";
import { listSavedAnalyses, listWatchlist } from "@/lib/server/phase2/repositories";
import { groupEventsByToken } from "@/lib/server/monitoring-core.mjs";

export type SessionContext = { userId: string; previousLastSeenAt: string | null } | null;

type TokenRecord = { mint_address?: string | null; name?: string | null; symbol?: string | null; logo_url?: string | null };
type TokenRelation = TokenRecord | TokenRecord[] | null;
type EvidenceRow = { evidence_type: string | null; before_value: unknown; after_value: unknown; source: string | null };
type EvidenceRelation = EvidenceRow | EvidenceRow[] | null;

type RiskReportRow = { id: string | null; token_id: string | null; overall_risk_score: number | string | null; overall_risk_label: string | null; confidence: number | string | null; holder_concentration_score?: number | string | null; generated_at: string | null; tokens?: TokenRelation };
type BehaviorEventRow = { id: string | null; token_id: string | null; event_type: string | null; severity: number | string | null; confidence: number | string | null; title: string | null; summary: string | null; detected_at: string | null; tokens?: TokenRelation; behavior_event_evidence?: EvidenceRelation };
type PlatformCountTable = "tokens" | "risk_reports" | "behavior_events" | "saved_analyses" | "watchlist_items" | "tracked_tokens";

export type IntelligenceToken = { reportId: string; tokenId: string; mintAddress: string; name: string | null; symbol: string | null; logoUrl: string | null; riskScore: number | null; riskLabel: string | null; confidence: number | null; holderConcentrationScore: number | null; generatedAt: string };
export type IntelligenceEvent = { id: string; tokenId: string; eventType: string; severity: number | null; confidence: number | null; title: string; summary: string; detectedAt: string; mintAddress: string; name: string | null; symbol: string | null; logoUrl: string | null; evidence: EvidenceRow[] };
export type TokenMovement = { mintAddress: string; name: string | null; symbol: string | null; logoUrl: string | null; changes: { label: string; before: string; after: string; reason: string }[]; latestAt: string };
export type WatchlistChange = TokenMovement & { tokenId: string | null };
export type WatchlistHealth = { healthy: number; warning: number; critical: number; unavailable: number };
export type IntelligenceEventGroup = ReturnType<typeof groupEventsByToken<IntelligenceEvent>>[number];
export type PlatformStatus = { lastIntelligenceRefresh: string | null; lastBehaviorDetection: string | null; trackedTokenCount: number | null; dueForScanCount: number | null; watchlistPriorityTokenCount: number | null; scannedLast24hCount: number | null; uniqueEventTokensLast24hCount: number | null; behaviorEventCount: number | null; savedAnalysesCount: number | null; watchlistCount: number | null };
export type IntelligenceData = { session: SessionContext; changesSinceLastVisit: IntelligenceEvent[]; timeline: IntelligenceEvent[]; eventGroups: IntelligenceEventGroup[]; holderGroups: IntelligenceEventGroup[]; authorityGroups: IntelligenceEventGroup[]; priority: IntelligenceEvent[]; watchlistHealth: WatchlistHealth | null; watchlistChanges: WatchlistChange[]; tokenMovements: TokenMovement[]; status: PlatformStatus };

function relationOne<T>(value: T | T[] | null | undefined): T | null { return Array.isArray(value) ? value[0] ?? null : value ?? null; }
function relationMany<T>(value: T | T[] | null | undefined): T[] { if (!value) return []; return Array.isArray(value) ? value : [value]; }
function str(value: unknown): string | null { return typeof value === "string" && value.length > 0 ? value : null; }
function num(value: unknown): number | null { const parsed = typeof value === "number" ? value : typeof value === "string" ? Number(value) : NaN; return Number.isFinite(parsed) ? parsed : null; }
function display(value: unknown) { if (value === null || value === undefined || value === "") return "Unavailable"; if (typeof value === "number") return Number.isInteger(value) ? String(value) : value.toFixed(2); if (typeof value === "object") return JSON.stringify(value); return String(value); }
function percent(value: number | null) { return value === null ? "Unavailable" : `${Math.round(value * 100)}%`; }
function levelBucket(label: string | null): keyof WatchlistHealth { const normalized = (label ?? "").toLowerCase(); if (normalized.includes("low")) return "healthy"; if (normalized.includes("medium")) return "warning"; if (normalized.includes("high")) return "critical"; return "unavailable"; }
function severityRank(event: IntelligenceEvent) { if ((event.severity ?? 0) >= 5) return 0; if (event.eventType === "authority_change") return 1; if ((event.severity ?? 0) >= 4) return 2; if (event.eventType === "holder_concentration_spike") return 4; if ((event.severity ?? 0) >= 2) return 5; return 6; }

function mapRisk(row: RiskReportRow): IntelligenceToken | null { const token = relationOne(row.tokens); const reportId = str(row.id); const tokenId = str(row.token_id); const mintAddress = str(token?.mint_address); const generatedAt = str(row.generated_at); if (!reportId || !tokenId || !mintAddress || !generatedAt) return null; return { reportId, tokenId, mintAddress, name: str(token?.name), symbol: str(token?.symbol), logoUrl: str(token?.logo_url), riskScore: num(row.overall_risk_score), riskLabel: str(row.overall_risk_label), confidence: num(row.confidence), holderConcentrationScore: num(row.holder_concentration_score), generatedAt }; }
function mapEvent(row: BehaviorEventRow): IntelligenceEvent | null { const token = relationOne(row.tokens); const id = str(row.id); const tokenId = str(row.token_id); const title = str(row.title); const summary = str(row.summary); const detectedAt = str(row.detected_at); const mintAddress = str(token?.mint_address); const eventType = str(row.event_type); if (!id || !tokenId || !title || !summary || !detectedAt || !mintAddress || !eventType) return null; return { id, tokenId, eventType, severity: num(row.severity), confidence: num(row.confidence), title, summary, detectedAt, mintAddress, name: str(token?.name), symbol: str(token?.symbol), logoUrl: str(token?.logo_url), evidence: relationMany(row.behavior_event_evidence) }; }

async function count(table: PlatformCountTable): Promise<number | null> { const { count, error } = await supabaseAdmin.from(table).select("id", { count: "exact", head: true }); if (error) { console.error(`[intelligence] count failed for ${table}:`, error.message); return null; } return count ?? null; }
async function loadRiskReports(): Promise<IntelligenceToken[]> { const { data, error } = await supabaseAdmin.from("risk_reports").select("id,token_id,overall_risk_score,overall_risk_label,confidence,holder_concentration_score,generated_at,tokens(mint_address,name,symbol,logo_url)").not("generated_at", "is", null).order("generated_at", { ascending: false }).limit(1000); if (error) { console.error("[intelligence] risk report load failed:", error.message); return []; } return ((data ?? []) as RiskReportRow[]).flatMap((row) => mapRisk(row) ?? []); }
async function loadEvents(limit = 100): Promise<IntelligenceEvent[]> { const { data, error } = await supabaseAdmin.from("behavior_events").select("id,token_id,event_type,severity,confidence,title,summary,detected_at,tokens(mint_address,name,symbol,logo_url),behavior_event_evidence(evidence_type,before_value,after_value,source)").order("detected_at", { ascending: false }).limit(limit); if (error) { console.error("[intelligence] behavior event load failed:", error.message); return []; } return ((data ?? []) as BehaviorEventRow[]).flatMap((row) => mapEvent(row) ?? []); }

function latestByToken(reports: IntelligenceToken[]) { const map = new Map<string, IntelligenceToken>(); for (const report of reports) { const existing = map.get(report.tokenId); if (!existing || report.generatedAt > existing.generatedAt) map.set(report.tokenId, report); } return map; }
function riskMovement(reports: IntelligenceToken[]): TokenMovement[] { const grouped = new Map<string, IntelligenceToken[]>(); for (const report of reports) grouped.set(report.tokenId, [...(grouped.get(report.tokenId) ?? []), report]); const movements: TokenMovement[] = []; for (const rows of grouped.values()) { const [latest, previous] = rows.sort((a, b) => b.generatedAt.localeCompare(a.generatedAt)); if (!latest || !previous) continue; const changes: TokenMovement["changes"] = []; if (latest.riskScore !== previous.riskScore) changes.push({ label: "Risk", before: display(previous.riskScore), after: display(latest.riskScore), reason: "Current stored risk report differs from the prior stored risk report." }); if (latest.riskLabel !== previous.riskLabel) changes.push({ label: "Risk Level", before: display(previous.riskLabel), after: display(latest.riskLabel), reason: "Risk level changed in the deterministic risk report." }); if (latest.confidence !== previous.confidence) changes.push({ label: "Confidence", before: display(previous.confidence), after: display(latest.confidence), reason: "Report confidence changed in stored risk output." }); if (latest.holderConcentrationScore !== previous.holderConcentrationScore) changes.push({ label: "Holder Concentration", before: display(previous.holderConcentrationScore), after: display(latest.holderConcentrationScore), reason: "Holder concentration score changed in stored risk output." }); if (changes.length) movements.push({ mintAddress: latest.mintAddress, name: latest.name, symbol: latest.symbol, logoUrl: latest.logoUrl, changes, latestAt: latest.generatedAt }); } return movements; }
function evidenceMovements(events: IntelligenceEvent[]): TokenMovement[] { return events.flatMap((event) => event.evidence.map((evidence) => ({ mintAddress: event.mintAddress, name: event.name, symbol: event.symbol, logoUrl: event.logoUrl, latestAt: event.detectedAt, changes: [{ label: event.eventType === "authority_change" ? "Authority" : "Holder Concentration", before: display(evidence.before_value), after: display(evidence.after_value), reason: event.summary }] }))); }
function watchlistDiffs(userId: string, reports: IntelligenceToken[], events: IntelligenceEvent[]) { return Promise.all([listWatchlist(userId), listSavedAnalyses(userId, 0, 999)]).then(([watchlist, saved]) => { const latest = latestByToken(reports); const latestSavedByMint = new Map<string, Awaited<ReturnType<typeof listSavedAnalyses>>["rows"][number]>(); for (const row of saved.rows) if (!latestSavedByMint.has(row.mint_address)) latestSavedByMint.set(row.mint_address, row); const health: WatchlistHealth = { healthy: 0, warning: 0, critical: 0, unavailable: 0 }; const changes: WatchlistChange[] = []; for (const item of watchlist) { const current = item.token_id ? latest.get(item.token_id) : null; health[levelBucket(current?.riskLabel ?? null)] += 1; const savedRow = latestSavedByMint.get(item.mint_address); const diff: WatchlistChange["changes"] = []; if (savedRow && current) { if (num(savedRow.risk_score) !== current.riskScore) diff.push({ label: "Risk Score", before: display(savedRow.risk_score), after: display(current.riskScore), reason: "Saved analysis snapshot differs from the current stored risk report." }); if ((savedRow.risk_level ?? null) !== current.riskLabel) diff.push({ label: "Risk Level", before: display(savedRow.risk_level), after: display(current.riskLabel), reason: "Risk level changed between saved snapshot and current report." }); if (num(savedRow.confidence) !== current.confidence) diff.push({ label: "Confidence", before: display(savedRow.confidence), after: display(current.confidence), reason: "Confidence changed between saved snapshot and current report." }); }
      const newEvents = events.filter((event) => event.mintAddress === item.mint_address && (!savedRow || event.detectedAt > savedRow.created_at));
      for (const event of newEvents.slice(0, 3)) diff.push({ label: "New Behavior Event", before: "No saved event", after: event.title, reason: event.summary });
      if (diff.length) changes.push({ tokenId: item.token_id, mintAddress: item.mint_address, name: item.tokens?.name ?? current?.name ?? null, symbol: item.tokens?.symbol ?? current?.symbol ?? null, logoUrl: item.tokens?.logo_url ?? current?.logoUrl ?? null, changes: diff, latestAt: current?.generatedAt ?? newEvents[0]?.detectedAt ?? item.created_at });
    }
    return { health, changes: changes.sort((a, b) => b.latestAt.localeCompare(a.latestAt)) };
  }); }

async function monitoringCount(kind: "due"|"watchlist"|"scanned24"|"eventTokens24"): Promise<number | null> { const now=new Date(); const dayAgo=new Date(now.getTime()-86400000).toISOString(); if(kind==="due") { const { count, error } = await supabaseAdmin.from("tracked_tokens").select("id", { count:"exact", head:true }).eq("is_active", true).lte("next_scan_at", now.toISOString()); if(error) return null; return count ?? null; } if(kind==="watchlist") { const { count, error } = await supabaseAdmin.from("tracked_tokens").select("id", { count:"exact", head:true }).contains("sources", ["watchlist"]); if(error) return null; return count ?? null; } if(kind==="scanned24") { const { count, error } = await supabaseAdmin.from("tracked_tokens").select("id", { count:"exact", head:true }).gte("last_scanned_at", dayAgo); if(error) return null; return count ?? null; } const { data, error } = await supabaseAdmin.from("behavior_events").select("token_id").gte("detected_at", dayAgo).limit(1000); if(error) return null; return new Set((data??[]).map((r)=>r.token_id)).size; }
export async function getIntelligenceData(session: SessionContext = null): Promise<IntelligenceData> { const [reports, events, trackedTokenCount, dueForScanCount, watchlistPriorityTokenCount, scannedLast24hCount, uniqueEventTokensLast24hCount, behaviorEventCount, savedAnalysesCount, watchlistCount] = await Promise.all([loadRiskReports(), loadEvents(), count("tracked_tokens"), monitoringCount("due"), monitoringCount("watchlist"), monitoringCount("scanned24"), monitoringCount("eventTokens24"), count("behavior_events"), count("saved_analyses"), count("watchlist_items")]); const watchlist = session ? await watchlistDiffs(session.userId, reports, events) : null; const timeline = events.sort((a, b) => b.detectedAt.localeCompare(a.detectedAt)); const previousLastSeenAt = session?.previousLastSeenAt ?? null; const changesSinceLastVisit = previousLastSeenAt ? timeline.filter((event) => event.detectedAt > previousLastSeenAt) : []; const riskMoves = riskMovement(reports); const tokenMovements = [...evidenceMovements(events), ...riskMoves].sort((a, b) => b.latestAt.localeCompare(a.latestAt)).slice(0, 20); return { session, changesSinceLastVisit, timeline: timeline.slice(0, 40), eventGroups: groupEventsByToken(timeline, "all").slice(0, 24), holderGroups: groupEventsByToken(timeline, "holders").slice(0, 24), authorityGroups: groupEventsByToken(timeline, "authorities").slice(0, 24), priority: [...timeline].sort((a, b) => severityRank(a) - severityRank(b) || b.detectedAt.localeCompare(a.detectedAt)).slice(0, 12), watchlistHealth: watchlist?.health ?? null, watchlistChanges: watchlist?.changes.slice(0, 20) ?? [], tokenMovements, status: { lastIntelligenceRefresh: reports[0]?.generatedAt ?? null, lastBehaviorDetection: timeline[0]?.detectedAt ?? null, trackedTokenCount, dueForScanCount, watchlistPriorityTokenCount, scannedLast24hCount, uniqueEventTokensLast24hCount, behaviorEventCount, savedAnalysesCount, watchlistCount } }; }
export const formatConfidenceValue = percent;
