export const TRACKING_PRIORITY = { watchlist: 100, analyzed: 80, saved_analysis: 60, trending: 40, system: 30, retained: 10 };
export const SCAN_INTERVAL_HOURS = { watchlist: 6, analyzed: 12, saved_analysis: 24, trending: 48, system: 48, retained: 168 };
export const MONITORING_BATCH_SIZE = 25;
export const ANALYZED_RETENTION_DAYS = 30;
export const HOLDER_CONCENTRATION_DELTA_THRESHOLD_PP = 10;
export const HOLDER_CONCENTRATION_VALUE_BUCKET_PP = 0.5;
const SOURCES = Object.keys(TRACKING_PRIORITY);
export function priorityForSource(source){ return TRACKING_PRIORITY[source] ?? 0; }
export function intervalHoursForPriority(priority){ if(priority>=TRACKING_PRIORITY.watchlist) return SCAN_INTERVAL_HOURS.watchlist; if(priority>=TRACKING_PRIORITY.analyzed) return SCAN_INTERVAL_HOURS.analyzed; if(priority>=TRACKING_PRIORITY.saved_analysis) return SCAN_INTERVAL_HOURS.saved_analysis; if(priority>=TRACKING_PRIORITY.trending) return SCAN_INTERVAL_HOURS.trending; return SCAN_INTERVAL_HOURS.retained; }
export function nextScanAt(now=new Date(), priority=0){ return new Date(now.getTime()+intervalHoursForPriority(priority)*3600_000).toISOString(); }
export function failureBackoffAt(failures, now=new Date()){ const hours=Math.min(24, 2 ** Math.min(Math.max(failures,1),5)); return new Date(now.getTime()+hours*3600_000).toISOString(); }
export function mergeSources(existing, source){ const set=new Set(Array.isArray(existing)?existing.filter(s=>SOURCES.includes(s)):[]); if(SOURCES.includes(source)) set.add(source); return [...set].sort((a,b)=>priorityForSource(b)-priorityForSource(a)||a.localeCompare(b)); }
export function mergedPriority(existingPriority, sources){ return Math.max(Number(existingPriority)||0, ...sources.map(priorityForSource)); }
export function materialValueBucket(value){ const n=Number(value); if(!Number.isFinite(n)) return 'na'; return String(Math.round(n/HOLDER_CONCENTRATION_VALUE_BUCKET_PP)*HOLDER_CONCENTRATION_VALUE_BUCKET_PP); }
export function eventFingerprint({tokenId,eventType,severity,beforeValue,afterValue,previousSnapshotId,currentSnapshotId,detectedAt}){ const d=detectedAt?new Date(detectedAt):new Date(); const windowStart=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate(),Math.floor(d.getUTCHours()/6)*6)); const before=beforeValue===null||beforeValue===undefined?'na':materialValueBucket(beforeValue); const after=afterValue===null||afterValue===undefined?'na':materialValueBucket(afterValue); return [tokenId,eventType,Math.floor(Number(severity)||0),before,after,previousSnapshotId??'no-prev',currentSnapshotId??'no-current',windowStart.toISOString()].join('|'); }
export function selectDueTrackedTokens(rows, nowIso=new Date().toISOString(), limit=MONITORING_BATCH_SIZE){ return rows.filter(r=>r.is_active!==false && (!r.next_scan_at || r.next_scan_at<=nowIso)).sort((a,b)=>(Number(b.priority)||0)-(Number(a.priority)||0)||String(a.last_scanned_at??'').localeCompare(String(b.last_scanned_at??''))||(Number(a.scan_failures)||0)-(Number(b.scan_failures)||0)||String(a.mint_address).localeCompare(String(b.mint_address))).slice(0,limit); }
export function shouldEmitHolderConcentration(previousPct,currentPct){ if(previousPct===null||previousPct===undefined||currentPct===null||currentPct===undefined) return false; const prev=Number(previousPct), cur=Number(currentPct); if(!Number.isFinite(prev)||!Number.isFinite(cur)) return false; return cur-prev>=HOLDER_CONCENTRATION_DELTA_THRESHOLD_PP; }
export function groupEventsByToken(events, filter='all'){ const match=e=>filter==='all'||(filter==='authorities'?e.eventType==='authority_change':filter==='holders'?e.eventType==='holder_concentration_spike':true); const sevRank=e=>e.severity??0; const map=new Map(); for(const e of events.filter(match)){ const g=map.get(e.tokenId)??{tokenId:e.tokenId,mintAddress:e.mintAddress,name:e.name??null,symbol:e.symbol??null,logoUrl:e.logoUrl??null,highestSeverity:null,count:0,latestAt:e.detectedAt,latestSummary:e.summary,eventTypes:new Set(),confidence:null,events:[]}; g.count++; g.highestSeverity=Math.max(g.highestSeverity??0,sevRank(e)); if(e.detectedAt>=g.latestAt){g.latestAt=e.detectedAt; g.latestSummary=e.summary; g.confidence=e.confidence??g.confidence;} g.eventTypes.add(e.eventType); g.events.push(e); map.set(e.tokenId,g); } return [...map.values()].map(g=>({...g,eventTypes:[...g.eventTypes].sort(),events:g.events.sort((a,b)=>b.detectedAt.localeCompare(a.detectedAt)).slice(0,3)})).sort((a,b)=>(b.highestSeverity??0)-(a.highestSeverity??0)||b.count-a.count||b.latestAt.localeCompare(a.latestAt)); }
