export const TRACKING_PRIORITY: Record<string, number>;
export const SCAN_INTERVAL_HOURS: Record<string, number>;
export const MONITORING_BATCH_SIZE: number;
export const ANALYZED_RETENTION_DAYS: number;
export const EVENT_RECURRENCE_WINDOW_HOURS: number;
export const HOLDER_CONCENTRATION_DELTA_THRESHOLD_PP: number;
export const HOLDER_CONCENTRATION_VALUE_BUCKET_PP: number;
export function priorityForSource(source:string): number;
export function effectiveSource(sources:unknown): string;
export function normalizeSources(sources:unknown): string[];
export function intervalHoursForPriority(priority:number): number;
export function nextScanAt(now?:Date, priority?:number): string;
export function failureBackoffAt(failures:number, now?:Date): string;
export function mergeSources(existing:unknown, source:string): string[];
export function removeSource(existing:unknown, source:string): string[];
export function priorityForSources(sources:unknown): number;
export function shouldRetainAnalyzed(lastRequestedAt:unknown, now?:Date): boolean;
export function materialValueBucket(value:unknown): string;
export function recurrenceWindowStart(value?:string|Date): string;
export function authorityState(mintAuthority:string|null|undefined, freezeAuthority:string|null|undefined): string;
export function eventFingerprint(params:{tokenId:string;eventType:string;severity:number;beforeValue?:unknown;afterValue?:unknown;detectedAt?:string|Date}): string;
export function holderEventFingerprint(params:{tokenId:string;severity:number;previousPct:unknown;currentPct:unknown;detectedAt?:string|Date}): string;
export function authorityEventFingerprint(params:{tokenId:string;severity:number;previousState:string;currentState:string;detectedAt?:string|Date}): string;
export function selectDueTrackedTokens<T extends {is_active?:boolean;next_scan_at?:string|null;priority?:number|null;last_scanned_at?:string|null;scan_failures?:number|null;mint_address:string}>(rows:T[], nowIso?:string, limit?:number): T[];
export function shouldEmitHolderConcentration(previousPct:unknown,currentPct:unknown): boolean;
export function groupEventsByToken<T extends {tokenId:string;mintAddress:string;name?:string|null;symbol?:string|null;logoUrl?:string|null;eventType:string;severity?:number|null;confidence?:number|null;summary:string;detectedAt:string}>(events:T[], filter?:string): Array<{tokenId:string;mintAddress:string;name:string|null;symbol:string|null;logoUrl:string|null;highestSeverity:number|null;count:number;latestAt:string;latestSummary:string;eventTypes:string[];confidence:number|null;events:T[]}>;
