import "server-only";
import { supabaseAdmin } from "./supabase-admin";
import { mergeSources, mergedPriority, nextScanAt, failureBackoffAt, MONITORING_BATCH_SIZE } from "./monitoring-core.mjs";
export { MONITORING_BATCH_SIZE };
export async function enrollTrackedToken(params:{tokenId:string; mintAddress:string; source:"analyzed"|"watchlist"|"saved_analysis"|"trending"|"system"}){ const now=new Date(); const { data: existing, error: lookupError }=await supabaseAdmin.from("tracked_tokens").select("id,sources,priority").eq("token_id",params.tokenId).maybeSingle(); if(lookupError) throw new Error(`tracked_token_lookup_failed:${lookupError.message}`); const sources=mergeSources(existing?.sources, params.source); const priority=mergedPriority(existing?.priority, sources); const payload={ token_id:params.tokenId, mint_address:params.mintAddress, source:sources[0]??params.source, sources, priority, is_active:true, last_requested_at:now.toISOString(), next_scan_at: nextScanAt(now, priority), updated_at: now.toISOString()}; const query= existing?.id ? supabaseAdmin.from("tracked_tokens").update(payload).eq("id", existing.id) : supabaseAdmin.from("tracked_tokens").insert(payload); const { error }=await query; if(error) throw new Error(`tracked_token_upsert_failed:${error.message}`); }
export async function safeEnrollTrackedToken(params:Parameters<typeof enrollTrackedToken>[0]){ try{ await enrollTrackedToken(params); }catch(error){ console.error("[monitoring] enrollment failed:", error instanceof Error ? error.message : String(error)); } }
export async function loadDueTrackedTokens(limit=MONITORING_BATCH_SIZE){ const { data, error }=await supabaseAdmin.from("tracked_tokens").select("id,token_id,mint_address,priority,last_scanned_at,next_scan_at,scan_failures,tokens(id,mint_address,symbol)").eq("is_active",true).lte("next_scan_at",new Date().toISOString()).order("priority",{ascending:false}).order("last_scanned_at",{ascending:true, nullsFirst:true}).order("scan_failures",{ascending:true}).limit(limit); if(error){ console.error("[monitoring] due token load failed:", error.message); return []; } return data??[]; }
export async function markTrackedTokenSuccess(id:string, priority:number){ const now=new Date(); await supabaseAdmin.from("tracked_tokens").update({ last_scanned_at:now.toISOString(), next_scan_at:nextScanAt(now,priority), scan_failures:0, updated_at:now.toISOString() }).eq("id",id); }
export async function markTrackedTokenFailure(id:string, failures:number){ const now=new Date(); await supabaseAdmin.from("tracked_tokens").update({ scan_failures:failures+1, next_scan_at:failureBackoffAt(failures+1,now), updated_at:now.toISOString() }).eq("id",id); }
