import "server-only";
import { supabaseAdmin } from "./supabase-admin";
import { effectiveSource, failureBackoffAt, mergeSources, MONITORING_BATCH_SIZE, nextScanAt, priorityForSources, removeSource, shouldRetainAnalyzed } from "./monitoring-core.mjs";
export { MONITORING_BATCH_SIZE };
type TrackingSource = "analyzed"|"watchlist"|"saved_analysis"|"trending"|"system"|"retained";
function trackingPayload(tokenId:string, mintAddress:string, sources:string[], now:Date){ const priority=priorityForSources(sources); return { token_id:tokenId, mint_address:mintAddress, source:effectiveSource(sources), sources, priority, is_active:true, last_requested_at:now.toISOString(), next_scan_at:nextScanAt(now, priority), updated_at:now.toISOString() }; }
export async function enrollTrackedToken(params:{tokenId:string; mintAddress:string; source:TrackingSource}){ const now=new Date(); const { data: existing, error: lookupError }=await supabaseAdmin.from("tracked_tokens").select("id,sources,priority").eq("token_id",params.tokenId).maybeSingle(); if(lookupError) throw new Error(`tracked_token_lookup_failed:${lookupError.message}`); const sources=mergeSources(existing?.sources, params.source); const payload=trackingPayload(params.tokenId, params.mintAddress, sources, now); const query= existing?.id ? supabaseAdmin.from("tracked_tokens").update(payload).eq("id", existing.id) : supabaseAdmin.from("tracked_tokens").insert(payload); const { error }=await query; if(error) throw new Error(`tracked_token_upsert_failed:${error.message}`); }
export async function safeEnrollTrackedToken(params:Parameters<typeof enrollTrackedToken>[0]){ try{ await enrollTrackedToken(params); }catch(error){ console.error("[monitoring] enrollment failed:", error instanceof Error ? error.message : String(error)); } }
export async function reconcileWatchlistTracking(mintAddress:string){ const { data: token, error: tokenError }=await supabaseAdmin.from("tokens").select("id,mint_address").eq("mint_address",mintAddress).maybeSingle(); if(tokenError||!token) return; const { count, error: countError }=await supabaseAdmin.from("watchlist_items").select("id",{count:"exact",head:true}).eq("mint_address",mintAddress); if(countError||Number(count??0)>0) return; const { data: tracked, error: trackedError }=await supabaseAdmin.from("tracked_tokens").select("id,sources,last_requested_at").eq("token_id",token.id).maybeSingle(); if(trackedError||!tracked) return; let sources=removeSource(tracked.sources,"watchlist"); if(sources.length===0 && shouldRetainAnalyzed(tracked.last_requested_at)) sources=["retained"]; const priority=priorityForSources(sources); const now=new Date(); await supabaseAdmin.from("tracked_tokens").update({ source:effectiveSource(sources), sources, priority, is_active:sources.length>0, next_scan_at:sources.length>0?nextScanAt(now,priority):null, updated_at:now.toISOString() }).eq("id",tracked.id); }
export async function safeReconcileWatchlistTracking(mintAddress:string){ try{ await reconcileWatchlistTracking(mintAddress); }catch(error){ console.error("[monitoring] watchlist reconciliation failed:", error instanceof Error ? error.message : String(error)); } }
export async function loadDueTrackedTokens(limit=MONITORING_BATCH_SIZE){ const { data, error }=await supabaseAdmin.from("tracked_tokens").select("id,token_id,mint_address,priority,last_scanned_at,next_scan_at,scan_failures,tokens(id,mint_address,symbol)").eq("is_active",true).lte("next_scan_at",new Date().toISOString()).order("priority",{ascending:false}).order("last_scanned_at",{ascending:true, nullsFirst:true}).order("scan_failures",{ascending:true}).limit(limit); if(error){ console.error("[monitoring] due token load failed:", error.message); return []; } return data??[]; }
export async function markTrackedTokenSuccess(id:string, priority:number){ const now=new Date(); await supabaseAdmin.from("tracked_tokens").update({ last_scanned_at:now.toISOString(), next_scan_at:nextScanAt(now,priority), scan_failures:0, updated_at:now.toISOString() }).eq("id",id); }
export async function markTrackedTokenFailure(id:string, failures:number){ const now=new Date(); await supabaseAdmin.from("tracked_tokens").update({ scan_failures:failures+1, next_scan_at:failureBackoffAt(failures+1,now), updated_at:now.toISOString() }).eq("id",id); }
