import "server-only";
import { supabaseAdmin } from "./supabase-admin";
import { asNumber, asRecord, asString, fetchJson } from "./providers/utils";

export type TrendingRisk = { score: number | null; label: string | null; generatedAt: string | null };
export type TrendingToken = { rank: number; mintAddress: string; tokenName: string | null; tokenSymbol: string | null; tokenLogoUrl: string | null; tokenCategory: string | null; trendingScore: number; priceUsd: number | null; priceChangePercent: number | null; priceChangeTimeframe: string; volumeUsd: number | null; volumeTimeframe: string; liquidityUsd: number | null; tradeCount: number | null; rankingComponents: Record<string, number>; rankingReason: string; source: string; sourceTimestamp: string; risk: TrendingRisk | null };
export type TrendingResult = { tokens: TrendingToken[]; provider: string; rankingTimeframe: string; sourceTimestamp: string | null; lastSuccessfulRefresh: string | null; status: "current" | "cached" | "unavailable"; error?: string };
type Candidate = Omit<TrendingToken, "rank" | "trendingScore" | "rankingComponents" | "rankingReason" | "risk"> & { txns24h: number | null; uniqueWallet24h: number | null; volumeChange24hPercent: number | null };
const PROVIDER = "Birdeye /defi/token_trending";
const RANKING_TIMEFRAME = "24 hours";
const MINT_RE = /^[1-9A-HJ-NP-Za-km-z]{32,44}$/;
function finite(value: number | null): value is number { return typeof value === "number" && Number.isFinite(value); }
function normalize(value: number, max: number) { return max > 0 ? Math.min(1, Math.max(0, value / max)) : 0; }
function category(item: Record<string, unknown>): string | null { const raw = asString(item.category) ?? asString(item.tokenType) ?? asString(item.type); if (!raw) return null; const n = raw.toLowerCase(); if (n.includes("stable")) return "Stablecoin"; if (n.includes("staking") || n.includes("lst")) return "Liquid Staking"; if (n.includes("defi")) return "DeFi"; if (n.includes("governance")) return "Governance"; if (n.includes("gaming") || n.includes("game")) return "Gaming"; if (n === "ai" || n.includes("artificial intelligence")) return "AI"; if (n.includes("infra")) return "Infrastructure"; if (n.includes("meme")) return "Memecoin"; return "Other"; }
function buildReason(token: TrendingToken) { const labels: Record<string, string> = { volume: "high 24-hour volume", tradeActivity: "elevated 24-hour trade activity", liquidity: "strong liquidity", participation: "available participant activity", priceMovement: "absolute 24-hour price movement" }; const parts = Object.entries(token.rankingComponents).sort((a, b) => b[1] - a[1]).slice(0, 3).map(([key]) => labels[key]).filter(Boolean); return `Ranked for ${parts.join(", ")}.`; }
function mapItem(item: unknown, sourceTimestamp: string): Candidate | null { const r = asRecord(item); const mint = asString(r.address) ?? asString(r.mint) ?? asString(r.tokenAddress); if (!mint || !MINT_RE.test(mint)) return null; const volumeUsd = asNumber(r.volume24hUSD) ?? asNumber(r.v24hUSD) ?? asNumber(r.volume24h) ?? asNumber(r.volume_24h_usd); const liquidityUsd = asNumber(r.liquidity) ?? asNumber(r.liquidityUsd) ?? asNumber(r.liquidity_usd); const txns24h = asNumber(r.txns24h) ?? asNumber(r.trade24h) ?? asNumber(r.trade24hCount) ?? asNumber(r.trade_count_24h); const priceUsd = asNumber(r.price) ?? asNumber(r.priceUsd) ?? asNumber(r.price_usd); const priceChangePercent = asNumber(r.priceChange24hPercent) ?? asNumber(r.priceChange24h) ?? asNumber(r.price_change_24h_percent); const uniqueWallet24h = asNumber(r.uniqueWallet24h) ?? asNumber(r.unique_wallet_24h) ?? asNumber(r.holder24h); const volumeChange24hPercent = asNumber(r.volumeChange24hPercent) ?? asNumber(r.volumeChange24h); if (![volumeUsd, liquidityUsd, txns24h, priceUsd, priceChangePercent, uniqueWallet24h, volumeChange24hPercent].some(finite)) return null; return { mintAddress: mint, tokenName: asString(r.name), tokenSymbol: asString(r.symbol), tokenLogoUrl: asString(r.logoURI) ?? asString(r.logoUri) ?? asString(r.logo), tokenCategory: category(r), priceUsd, priceChangePercent, priceChangeTimeframe: "24h", volumeUsd, volumeTimeframe: "24h", liquidityUsd, tradeCount: txns24h, txns24h, uniqueWallet24h, volumeChange24hPercent, source: PROVIDER, sourceTimestamp }; }
function score(candidates: Candidate[]): TrendingToken[] { const maxima = { volume: Math.max(...candidates.map((c) => c.volumeUsd ?? 0)), volumeGrowth: Math.max(...candidates.map((c) => Math.max(0, c.volumeChange24hPercent ?? 0))), tradeActivity: Math.max(...candidates.map((c) => c.txns24h ?? 0)), liquidity: Math.max(...candidates.map((c) => c.liquidityUsd ?? 0)), participation: Math.max(...candidates.map((c) => c.uniqueWallet24h ?? 0)), priceMovement: Math.max(...candidates.map((c) => Math.abs(c.priceChangePercent ?? 0))) }; const base = { volume: 0.35, tradeActivity: 0.25, liquidity: 0.2, participation: 0.1, priceMovement: 0.1 }; return candidates.map((c) => { const raw: Record<string, number | null> = { volume: finite(c.volumeUsd) ? normalize(c.volumeUsd, maxima.volume) : finite(c.volumeChange24hPercent) ? normalize(Math.max(0, c.volumeChange24hPercent), maxima.volumeGrowth) : null, tradeActivity: finite(c.txns24h) ? normalize(c.txns24h, maxima.tradeActivity) : null, liquidity: finite(c.liquidityUsd) ? normalize(c.liquidityUsd, maxima.liquidity) : null, participation: finite(c.uniqueWallet24h) ? normalize(c.uniqueWallet24h, maxima.participation) : null, priceMovement: finite(c.priceChangePercent) ? normalize(Math.abs(c.priceChangePercent), maxima.priceMovement) : null }; const available = Object.entries(raw).filter(([, v]) => v !== null && v > 0) as [keyof typeof base, number][]; const weightTotal = available.reduce((sum, [k]) => sum + base[k], 0); const rankingComponents = Object.fromEntries(available.map(([k, v]) => [k, Math.round((base[k] / weightTotal) * v * 10000) / 100])) as Record<string, number>; const trendingScore = Math.round(Object.values(rankingComponents).reduce((a, b) => a + b, 0) * 100) / 100; return { ...c, rank: 0, trendingScore, rankingComponents, rankingReason: "", risk: null }; }).sort((a, b) => b.trendingScore - a.trendingScore || (b.volumeUsd ?? -1) - (a.volumeUsd ?? -1) || a.mintAddress.localeCompare(b.mintAddress)).slice(0, 10).map((t, i) => ({ ...t, rank: i + 1, rankingReason: buildReason({ ...t, rank: i + 1 }) })); }
async function attachRisk(tokens: TrendingToken[]) { const { data } = await supabaseAdmin.from("tokens").select("mint_address,risk_reports(overall_risk_score,overall_risk_label,generated_at)").in("mint_address", tokens.map((t) => t.mintAddress)); const map = new Map<string, TrendingRisk>(); for (const row of (data ?? []) as { mint_address: string; risk_reports?: { overall_risk_score: number | null; overall_risk_label: string | null; generated_at: string | null }[] }[]) { const latest = [...(row.risk_reports ?? [])].sort((a, b) => String(b.generated_at).localeCompare(String(a.generated_at)))[0]; if (latest) map.set(row.mint_address, { score: latest.overall_risk_score, label: latest.overall_risk_label, generatedAt: latest.generated_at }); } return tokens.map((t) => ({ ...t, risk: map.get(t.mintAddress) ?? null })); }
async function persist(tokens: TrendingToken[]) { if (!tokens.length) return; await supabaseAdmin.from("trending_snapshots").insert(tokens.map((t) => ({ mint_address: t.mintAddress, token_name: t.tokenName, token_symbol: t.tokenSymbol, token_logo_url: t.tokenLogoUrl, token_category: t.tokenCategory, rank: t.rank, trending_score: t.trendingScore, price_usd: t.priceUsd, price_change_percent: t.priceChangePercent, price_change_timeframe: t.priceChangeTimeframe, volume_usd: t.volumeUsd, volume_timeframe: t.volumeTimeframe, liquidity_usd: t.liquidityUsd, trade_count: t.tradeCount, ranking_components: t.rankingComponents, ranking_reason: t.rankingReason, source: t.source, source_timestamp: t.sourceTimestamp }))); }
async function cached(): Promise<TrendingResult | null> { const { data } = await supabaseAdmin.from("trending_snapshots").select("*").order("created_at", { ascending: false }).limit(100); const latestCreated = (data?.[0] as { created_at?: string } | undefined)?.created_at; if (!latestCreated) return null; const rows = (data ?? []).filter((r) => (r as { created_at?: string }).created_at === latestCreated).sort((a, b) => ((a as { rank: number }).rank - (b as { rank: number }).rank)); const tokens = await attachRisk(rows.map((r) => ({ rank: r.rank, mintAddress: r.mint_address, tokenName: r.token_name, tokenSymbol: r.token_symbol, tokenLogoUrl: r.token_logo_url, tokenCategory: r.token_category, trendingScore: Number(r.trending_score), priceUsd: r.price_usd, priceChangePercent: r.price_change_percent, priceChangeTimeframe: r.price_change_timeframe, volumeUsd: r.volume_usd, volumeTimeframe: r.volume_timeframe, liquidityUsd: r.liquidity_usd, tradeCount: r.trade_count, rankingComponents: r.ranking_components ?? {}, rankingReason: r.ranking_reason, source: r.source, sourceTimestamp: r.source_timestamp, risk: null }))); return { tokens, provider: PROVIDER, rankingTimeframe: RANKING_TIMEFRAME, sourceTimestamp: tokens[0]?.sourceTimestamp ?? null, lastSuccessfulRefresh: latestCreated, status: "cached" }; }
export async function getTrendingTokens(): Promise<TrendingResult> { const key = process.env.BIRDEYE_API_KEY; if (!key) return (await cached()) ?? { tokens: [], provider: PROVIDER, rankingTimeframe: RANKING_TIMEFRAME, sourceTimestamp: null, lastSuccessfulRefresh: null, status: "unavailable", error: "BIRDEYE_API_KEY is not configured" }; try { const sourceTimestamp = new Date().toISOString(); const json = await fetchJson("https://public-api.birdeye.so/defi/token_trending?sort_by=rank&sort_type=asc&offset=0&limit=50", { headers: { accept: "application/json", "X-API-KEY": key, "x-chain": "solana" }, next: { revalidate: 120 } }); const data = asRecord(json).data; const items = Array.isArray(asRecord(data).tokens) ? asRecord(data).tokens as unknown[] : Array.isArray(asRecord(data).items) ? asRecord(data).items as unknown[] : Array.isArray(data) ? data as unknown[] : []; const deduped = Array.from(new Map(items.map((i) => mapItem(i, sourceTimestamp)).filter(Boolean).map((c) => [c!.mintAddress, c!] as const)).values()); const tokens = await attachRisk(score(deduped)); if (tokens.length < 10) throw new Error("Provider returned fewer than 10 eligible Solana tokens"); await persist(tokens); return { tokens, provider: PROVIDER, rankingTimeframe: RANKING_TIMEFRAME, sourceTimestamp, lastSuccessfulRefresh: new Date().toISOString(), status: "current" }; } catch (error) { return (await cached()) ?? { tokens: [], provider: PROVIDER, rankingTimeframe: RANKING_TIMEFRAME, sourceTimestamp: null, lastSuccessfulRefresh: null, status: "unavailable", error: error instanceof Error ? error.message : "Unknown provider failure" }; } }
