import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { cookies } from "next/headers";
import { SESSION_COOKIE_NAME } from "@/lib/server/auth/config";
import { validateSessionToken } from "@/lib/server/auth/session";
import { getSavedAnalysis } from "@/lib/server/phase2/repositories";
import { formatConfidence, isUuid } from "@/lib/server/phase2/validation";
import { Shell, Risk, fmt, short } from "../../ui";
export default async function AnalysisDetail({params}:{params:Promise<{id:string}>}){ const session=await validateSessionToken((await cookies()).get(SESSION_COOKIE_NAME)?.value); if(!session) redirect("/"); const {id}=await params; if(!isUuid(id)) notFound(); const a=await getSavedAnalysis(session.userId,id); if(!a) notFound(); return <Shell><article className="rounded-2xl border border-border bg-background p-6"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-accent">Saved Intelligence Snapshot</p><h1 className="mt-2 font-display text-3xl font-semibold">{a.tokens?.symbol ?? a.tokens?.name ?? short(a.mint_address)}</h1><p className="mt-2 font-mono text-sm text-muted">{a.mint_address}</p><div className="mt-5"><Risk score={a.risk_score} level={a.risk_level}/></div><dl className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-lg bg-surface p-3"><dt className="text-xs text-muted">Confidence at save time</dt><dd>{formatConfidence(a.confidence)}</dd></div><div className="rounded-lg bg-surface p-3"><dt className="text-xs text-muted">Analyzed at</dt><dd>{fmt(a.analyzed_at)}</dd></div><div className="rounded-lg bg-surface p-3"><dt className="text-xs text-muted">Saved at</dt><dd>{fmt(a.created_at)}</dd></div></dl><section className="mt-6"><h2 className="font-display text-xl font-semibold">Reasons at save time</h2>{a.reasons.length?<ul className="mt-2 list-disc pl-5 text-sm text-muted">{a.reasons.map((r,i)=><li key={i}>{typeof r==='string'?r:JSON.stringify(r)}</li>)}</ul>:<p className="mt-2 text-sm text-muted">No reasons were available in the saved report.</p>}</section><section className="mt-6"><h2 className="font-display text-xl font-semibold">AI explanation at save time</h2><p className="mt-2 whitespace-pre-wrap text-sm text-muted">{a.ai_explanation ?? "No AI explanation was available."}</p></section><details className="mt-6"><summary className="cursor-pointer text-sm text-accent">Source metadata</summary><pre className="mt-2 overflow-auto rounded-lg bg-surface p-3 text-xs">{JSON.stringify(a.source_metadata,null,2)}</pre></details><Link className="mt-6 inline-block text-accent" href={`/token/${a.mint_address}`}>Open current token intelligence</Link></article></Shell> }
