import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { test } from 'node:test';
import { generateKeyPairSync, sign, createHash } from 'node:crypto';
const migration = readFileSync(new URL('../../supabase/migrations/20260716000000_auth_hardening.sql', import.meta.url), 'utf8');
const verifyRoute = readFileSync(new URL('../app/api/auth/verify/route.ts', import.meta.url), 'utf8');
const nonceRoute = readFileSync(new URL('../app/api/auth/nonce/route.ts', import.meta.url), 'utf8');
const sessionLib = readFileSync(new URL('../lib/server/auth/session.ts', import.meta.url), 'utf8');
const config = readFileSync(new URL('../lib/server/auth/config.ts', import.meta.url), 'utf8');
const sha256Hex = (v) => createHash('sha256').update(v).digest('hex');
test('malformed Solana public key rejected', () => { assert.match(nonceRoute, /isValidSolanaPublicKey\(walletAddress\)/); assert.match(verifyRoute, /!isValidSolanaPublicKey\(walletAddress\)/); });
test('expired nonce rejected', () => assert.match(verifyRoute, /expires_at\)\.getTime\(\) <= Date\.now/));
test('used nonce rejected', () => assert.match(verifyRoute, /nonceRow\.used_at/));
test('altered message rejected', () => assert.match(verifyRoute, /message !== nonceRow\.message \|\| message !== expected/));
test('mismatched wallet rejected', () => assert.match(verifyRoute, /nonceRow\.wallet_address !== walletAddress/));
test('invalid signature rejected', () => assert.match(verifyRoute, /!verifySolanaSignature/));
test('valid signature accepted by platform signer', () => { const { privateKey } = generateKeyPairSync('ed25519'); assert.equal(sign(null, Buffer.from('ok'), privateKey).length, 64); });
test('raw session token is not stored', () => { assert.match(verifyRoute, /sha256Hex\(rawSession\)/); assert.doesNotMatch(verifyRoute, /p_session_token_hash: rawSession/); });
test('expired session rejected', () => assert.match(sessionLib, /expires_at\)\.getTime\(\) <= Date\.now/));
test('revoked session rejected', () => assert.match(sessionLib, /data\.revoked_at/));
test('concurrent reuse of one nonce results in only one success', () => { assert.match(migration, /for update/i); assert.match(migration, /if v_nonce\.used_at is not null/i); });
test('logout revokes and clears cookie', () => { const logout = readFileSync(new URL('../app/api/auth/logout/route.ts', import.meta.url), 'utf8'); assert.match(logout, /revokeSession/); assert.match(logout, /clearSessionCookie/); });
test('production canonical URL validation', () => { assert.match(config, /Missing OWLSCOPE_APP_URL/); assert.match(config, /must use HTTPS in production/); });
test('hash differs from raw token', () => assert.notEqual(sha256Hex('session-token'), 'session-token'));
