import test from 'node:test';
import assert from 'node:assert/strict';
import { mergeSources, mergedPriority, selectDueTrackedTokens, nextScanAt, failureBackoffAt, eventFingerprint, shouldEmitHolderConcentration, groupEventsByToken } from '../lib/server/monitoring-core.mjs';

test('monitoring onboarding merges sources idempotently and preserves higher priority',()=>{ const sources=mergeSources(['watchlist'],'analyzed'); assert.deepEqual(sources,['watchlist','analyzed']); assert.equal(mergedPriority(100,sources),100); assert.deepEqual(mergeSources(sources,'watchlist'),sources); });
test('scheduler selects only due active tokens by priority and enforces batch limit',()=>{ const now='2026-07-16T00:00:00.000Z'; const rows=[{mint_address:'low',is_active:true,next_scan_at:now,priority:10,last_scanned_at:'2026-07-15',scan_failures:0},{mint_address:'future',is_active:true,next_scan_at:'2026-07-17T00:00:00.000Z',priority:100},{mint_address:'off',is_active:false,next_scan_at:now,priority:100},{mint_address:'high',is_active:true,next_scan_at:now,priority:100,last_scanned_at:null,scan_failures:0}]; assert.deepEqual(selectDueTrackedTokens(rows,now,2).map(r=>r.mint_address),['high','low']); });
test('scan schedules success and failure deterministically',()=>{ const now=new Date('2026-07-16T00:00:00.000Z'); assert.equal(nextScanAt(now,100),'2026-07-16T06:00:00.000Z'); assert.equal(nextScanAt(now,80),'2026-07-16T12:00:00.000Z'); assert.equal(failureBackoffAt(3,now),'2026-07-16T08:00:00.000Z'); });
test('dedup fingerprint is stable for identical retries but changes for material values and event types',()=>{ const base={tokenId:'t',eventType:'holder_concentration_spike',severity:4,beforeValue:38.2,afterValue:38.2,previousSnapshotId:'s1',currentSnapshotId:'s2',detectedAt:'2026-07-16T01:00:00.000Z'}; assert.equal(eventFingerprint(base),eventFingerprint(base)); assert.notEqual(eventFingerprint(base),eventFingerprint({...base,afterValue:44.5})); assert.notEqual(eventFingerprint(base),eventFingerprint({...base,eventType:'authority_change'})); });
test('holder concentration requires a previous numeric baseline and meaningful increase',()=>{ assert.equal(shouldEmitHolderConcentration(null,38.2),false); assert.equal(shouldEmitHolderConcentration(38.2,38.2),false); assert.equal(shouldEmitHolderConcentration(38.2,49),true); });
test('feed grouping filters real matching events and sorts by severity count recency',()=>{ const events=[{id:'1',tokenId:'a',mintAddress:'mintA',eventType:'holder_concentration_spike',severity:4,confidence:.9,summary:'holder',detectedAt:'2026-07-16T00:00:00.000Z'},{id:'2',tokenId:'a',mintAddress:'mintA',eventType:'holder_concentration_spike',severity:4,confidence:.9,summary:'holder2',detectedAt:'2026-07-16T01:00:00.000Z'},{id:'3',tokenId:'b',mintAddress:'mintB',eventType:'authority_change',severity:5,confidence:.99,summary:'auth',detectedAt:'2026-07-15T00:00:00.000Z'}]; const all=groupEventsByToken(events,'all'); assert.deepEqual(all.map(g=>g.mintAddress),['mintB','mintA']); assert.equal(all[1].count,2); assert.equal(groupEventsByToken(events,'holders').length,1); assert.equal(groupEventsByToken([],'all').length,0); });
