import test from 'node:test';
import assert from 'node:assert/strict';
import { authorityEventFingerprint, authorityState, holderEventFingerprint, mergeSources, effectiveSource, priorityForSources, selectDueTrackedTokens, shouldEmitHolderConcentration } from '../lib/server/monitoring-core.mjs';

class PersistedEvents { constructor(){ this.rows=[]; this.unique=new Set(); } insert(row, role='service_role'){ if(role!=='service_role') throw new Error('permission_denied'); if(row.event_fingerprint && this.unique.has(row.event_fingerprint)) return null; const persisted={id:`event-${this.rows.length+1}`,...row}; this.rows.push(persisted); if(row.event_fingerprint) this.unique.add(row.event_fingerprint); return persisted; } }
class TrackedTokensTable { constructor(){ this.rows=[]; } upsert(row, role='service_role'){ if(role!=='service_role') throw new Error('permission_denied'); const existing=this.rows.find(r=>r.token_id===row.token_id||r.mint_address===row.mint_address); if(existing) Object.assign(existing,row); else this.rows.push({id:`tracked-${this.rows.length+1}`,...row}); return existing??this.rows.at(-1); } selectDue(now, limit, role='service_role'){ if(role!=='service_role') throw new Error('permission_denied'); return selectDueTrackedTokens(this.rows, now, limit); } }
function trackingPayload(existingSources, source){ const sources=mergeSources(existingSources, source); return { sources, source:effectiveSource(sources), priority:priorityForSources(sources), is_active:true }; }
function emit(events, fp){ return events.insert({token_id:'token-a',event_fingerprint:fp}); }

test('active to revoked retry on the same authority snapshot creates one event',()=>{ const events=new PersistedEvents(); const active=authorityState('addrA',null); const revoked=authorityState(null,null); const fp=authorityEventFingerprint({tokenId:'token-a',severity:3,previousState:active,currentState:revoked,currentSnapshotId:'auth-2'}); assert.ok(emit(events,fp)); assert.equal(emit(events,fp),null); assert.equal(events.rows.length,1); });
test('active to revoked, revoked to active, active to revoked again creates three events',()=>{ const events=new PersistedEvents(); const active=authorityState('addrA',null); const revoked=authorityState(null,null); emit(events,authorityEventFingerprint({tokenId:'token-a',severity:3,previousState:active,currentState:revoked,currentSnapshotId:'auth-2'})); emit(events,authorityEventFingerprint({tokenId:'token-a',severity:3,previousState:revoked,currentState:active,currentSnapshotId:'auth-3'})); emit(events,authorityEventFingerprint({tokenId:'token-a',severity:3,previousState:active,currentState:revoked,currentSnapshotId:'auth-4'})); assert.equal(events.rows.length,3); });
test('same holder transition retry using the same current snapshot creates one event',()=>{ const events=new PersistedEvents(); const fp=holderEventFingerprint({tokenId:'token-a',severity:4,previousPct:38.2,currentPct:49,currentSnapshotId:'holder-2'}); assert.ok(emit(events,fp)); assert.equal(emit(events,fp),null); assert.equal(events.rows.length,1); });
test('holder value falls and later crosses threshold again on a new snapshot creates a new event',()=>{ const events=new PersistedEvents(); emit(events,holderEventFingerprint({tokenId:'token-a',severity:4,previousPct:38.2,currentPct:49,currentSnapshotId:'holder-2'})); assert.equal(shouldEmitHolderConcentration(49,39),false); assert.equal(shouldEmitHolderConcentration(39,51),true); emit(events,holderEventFingerprint({tokenId:'token-a',severity:4,previousPct:39,currentPct:51,currentSnapshotId:'holder-4'})); assert.equal(events.rows.length,2); });
test('unchanged state on a new snapshot creates no event',()=>{ const events=new PersistedEvents(); if(shouldEmitHolderConcentration(49,49)) emit(events,holderEventFingerprint({tokenId:'token-a',severity:4,previousPct:49,currentPct:49,currentSnapshotId:'holder-3'})); assert.equal(events.rows.length,0); });
test('concurrent retries of the same transition create one persisted event',()=>{ const events=new PersistedEvents(); const fp=holderEventFingerprint({tokenId:'token-a',severity:4,previousPct:38.2,currentPct:49,currentSnapshotId:'holder-2'}); const results=[emit(events,fp),emit(events,fp),emit(events,fp)]; assert.equal(results.filter(Boolean).length,1); assert.equal(events.rows.length,1); });
test('tracked-token upsert preserves source membership and scheduler order',()=>{ const table=new TrackedTokensTable(); let payload=trackingPayload([], 'analyzed'); table.upsert({token_id:'token-a',mint_address:'mintA',next_scan_at:'2026-07-16T00:00:00.000Z',last_scanned_at:null,scan_failures:0,...payload}); payload=trackingPayload(payload.sources,'watchlist'); table.upsert({token_id:'token-a',mint_address:'mintA',next_scan_at:'2026-07-16T00:00:00.000Z',last_scanned_at:null,scan_failures:0,...payload}); table.upsert({token_id:'token-b',mint_address:'mintB',next_scan_at:'2026-07-16T00:00:00.000Z',last_scanned_at:null,scan_failures:0,...trackingPayload([], 'saved_analysis')}); assert.deepEqual(table.rows[0].sources,['watchlist','analyzed']); assert.equal(table.rows[0].source,'watchlist'); assert.deepEqual(table.selectDue('2026-07-16T00:00:00.000Z',1).map(r=>r.mint_address),['mintA']); });
test('service-role operations succeed while anon direct access is denied in the persistence simulation',()=>{ const events=new PersistedEvents(); const tracked=new TrackedTokensTable(); assert.doesNotThrow(()=>events.insert({token_id:'token-a',event_fingerprint:'fp'}, 'service_role')); assert.throws(()=>events.insert({token_id:'token-a',event_fingerprint:'fp2'}, 'anon'),/permission_denied/); assert.doesNotThrow(()=>tracked.upsert({token_id:'token-a',mint_address:'mintA',sources:['analyzed'],source:'analyzed',priority:80}, 'service_role')); assert.throws(()=>tracked.selectDue('2026-07-16T00:00:00.000Z',1,'anon'),/permission_denied/); });
