import test from 'node:test';
import assert from 'node:assert/strict';
import { holderEventFingerprint, mergeSources, effectiveSource, priorityForSources, selectDueTrackedTokens } from '../lib/server/monitoring-core.mjs';

class BehaviorEventsTable { constructor(){ this.rows=[]; this.unique=new Set(); } insert(row, role='service_role'){ if(role!=='service_role') throw new Error('permission_denied'); if(row.event_fingerprint && this.unique.has(row.event_fingerprint)) return null; const persisted={id:`event-${this.rows.length+1}`,...row}; this.rows.push(persisted); if(row.event_fingerprint) this.unique.add(row.event_fingerprint); return persisted; } }
class TrackedTokensTable { constructor(){ this.rows=[]; } upsert(row, role='service_role'){ if(role!=='service_role') throw new Error('permission_denied'); const existing=this.rows.find(r=>r.token_id===row.token_id||r.mint_address===row.mint_address); if(existing) Object.assign(existing,row); else this.rows.push({id:`tracked-${this.rows.length+1}`,...row}); return existing??this.rows.at(-1); } selectDue(now, limit, role='service_role'){ if(role!=='service_role') throw new Error('permission_denied'); return selectDueTrackedTokens(this.rows, now, limit); } }
function trackingPayload(existingSources, source){ const sources=mergeSources(existingSources, source); return { sources, source:effectiveSource(sources), priority:priorityForSources(sources), is_active:true }; }

test('database unique fingerprint behavior deduplicates concurrent material duplicates',()=>{ const table=new BehaviorEventsTable(); const fp=holderEventFingerprint({tokenId:'token-a',severity:4,previousPct:38.2,currentPct:49,detectedAt:'2026-07-16T01:00:00Z'}); const first=table.insert({token_id:'token-a',event_type:'holder_concentration_spike',event_fingerprint:fp}); const second=table.insert({token_id:'token-a',event_type:'holder_concentration_spike',event_fingerprint:fp}); assert.equal(first.id,'event-1'); assert.equal(second,null); assert.equal(table.rows.length,1); });
test('different snapshot ids with identical material transition still deduplicate',()=>{ const table=new BehaviorEventsTable(); const fpA=holderEventFingerprint({tokenId:'token-a',severity:4,previousPct:38.2,currentPct:49,detectedAt:'2026-07-16T01:00:00Z'}); const fpB=holderEventFingerprint({tokenId:'token-a',severity:4,previousPct:38.2,currentPct:49,detectedAt:'2026-07-16T02:00:00Z'}); table.insert({token_id:'token-a',event_fingerprint:fpA,evidence:{previous_snapshot_id:'snap-1',current_snapshot_id:'snap-2'}}); table.insert({token_id:'token-a',event_fingerprint:fpB,evidence:{previous_snapshot_id:'snap-3',current_snapshot_id:'snap-4'}}); assert.equal(fpA,fpB); assert.equal(table.rows.length,1); });
test('materially different holder transition creates a new event',()=>{ const table=new BehaviorEventsTable(); const fpA=holderEventFingerprint({tokenId:'token-a',severity:4,previousPct:38.2,currentPct:49,detectedAt:'2026-07-16T01:00:00Z'}); const fpB=holderEventFingerprint({tokenId:'token-a',severity:4,previousPct:49,currentPct:61,detectedAt:'2026-07-16T02:00:00Z'}); table.insert({token_id:'token-a',event_fingerprint:fpA}); table.insert({token_id:'token-a',event_fingerprint:fpB}); assert.equal(table.rows.length,2); });
test('tracked-token upsert preserves source membership and scheduler order',()=>{ const table=new TrackedTokensTable(); let payload=trackingPayload([], 'analyzed'); table.upsert({token_id:'token-a',mint_address:'mintA',next_scan_at:'2026-07-16T00:00:00.000Z',last_scanned_at:null,scan_failures:0,...payload}); payload=trackingPayload(payload.sources,'watchlist'); table.upsert({token_id:'token-a',mint_address:'mintA',next_scan_at:'2026-07-16T00:00:00.000Z',last_scanned_at:null,scan_failures:0,...payload}); table.upsert({token_id:'token-b',mint_address:'mintB',next_scan_at:'2026-07-16T00:00:00.000Z',last_scanned_at:null,scan_failures:0,...trackingPayload([], 'saved_analysis')}); assert.deepEqual(table.rows[0].sources,['watchlist','analyzed']); assert.equal(table.rows[0].source,'watchlist'); assert.deepEqual(table.selectDue('2026-07-16T00:00:00.000Z',1).map(r=>r.mint_address),['mintA']); });
test('service-role operations succeed while anon direct access is denied',()=>{ const events=new BehaviorEventsTable(); const tracked=new TrackedTokensTable(); assert.doesNotThrow(()=>events.insert({token_id:'token-a',event_fingerprint:'fp'}, 'service_role')); assert.throws(()=>events.insert({token_id:'token-a',event_fingerprint:'fp2'}, 'anon'),/permission_denied/); assert.doesNotThrow(()=>tracked.upsert({token_id:'token-a',mint_address:'mintA',sources:['analyzed'],source:'analyzed',priority:80}, 'service_role')); assert.throws(()=>tracked.selectDue('2026-07-16T00:00:00.000Z',1,'anon'),/permission_denied/); });
