import test from 'node:test';
import assert from 'node:assert/strict';
import { authorityEventFingerprint, authorityState, effectiveSource, holderEventFingerprint, mergeSources, normalizeSources, priorityForSources, removeSource, selectDueTrackedTokens, nextScanAt, failureBackoffAt, shouldEmitHolderConcentration, groupEventsByToken } from '../lib/server/monitoring-core.mjs';

test('monitoring onboarding merges analyzed, watchlist, and saved_analysis idempotently with one effective source',()=>{ let sources=mergeSources([], 'analyzed'); sources=mergeSources(sources,'watchlist'); sources=mergeSources(sources,'saved_analysis'); sources=mergeSources(sources,'watchlist'); assert.deepEqual(sources,['watchlist','analyzed','saved_analysis']); assert.equal(effectiveSource(sources),'watchlist'); assert.equal(priorityForSources(sources),100); });
test('watchlist removal recomputes effective source and retains other reasons',()=>{ const afterOneUserRemoval=normalizeSources(['watchlist','analyzed','saved_analysis']); assert.equal(effectiveSource(afterOneUserRemoval),'watchlist'); const afterLastWatcher=removeSource(afterOneUserRemoval,'watchlist'); assert.deepEqual(afterLastWatcher,['analyzed','saved_analysis']); assert.equal(effectiveSource(afterLastWatcher),'analyzed'); assert.equal(priorityForSources(afterLastWatcher),80); });
test('scheduler selects only due active tokens by priority and enforces batch limit',()=>{ const now='2026-07-16T00:00:00.000Z'; const rows=[{mint_address:'low',is_active:true,next_scan_at:now,priority:10,last_scanned_at:'2026-07-15',scan_failures:0},{mint_address:'future',is_active:true,next_scan_at:'2026-07-17T00:00:00.000Z',priority:100},{mint_address:'off',is_active:false,next_scan_at:now,priority:100},{mint_address:'high',is_active:true,next_scan_at:now,priority:100,last_scanned_at:null,scan_failures:0}]; assert.deepEqual(selectDueTrackedTokens(rows,now,2).map(r=>r.mint_address),['high','low']); });
test('scan schedules success and failure deterministically',()=>{ const now=new Date('2026-07-16T00:00:00.000Z'); assert.equal(nextScanAt(now,100),'2026-07-16T06:00:00.000Z'); assert.equal(nextScanAt(now,80),'2026-07-16T12:00:00.000Z'); assert.equal(failureBackoffAt(3,now),'2026-07-16T08:00:00.000Z'); });
test('holder fingerprint ignores snapshot ids but changes for material transitions',()=>{ const a=holderEventFingerprint({tokenId:'t',severity:4,previousPct:38.2,currentPct:49,detectedAt:'2026-07-16T01:00:00.000Z'}); const retryDifferentSnapshots=holderEventFingerprint({tokenId:'t',severity:4,previousPct:38.2,currentPct:49,detectedAt:'2026-07-16T02:00:00.000Z'}); const changed=holderEventFingerprint({tokenId:'t',severity:4,previousPct:49,currentPct:61,detectedAt:'2026-07-16T02:00:00.000Z'}); assert.equal(a,retryDifferentSnapshots); assert.notEqual(a,changed); });
test('authority fingerprint uses actual authority transition states',()=>{ const active=authorityState('addrA',null); const revoked=authorityState(null,null); assert.equal(authorityEventFingerprint({tokenId:'t',severity:3,previousState:active,currentState:revoked,detectedAt:'2026-07-16T00:00:00.000Z'}),authorityEventFingerprint({tokenId:'t',severity:3,previousState:active,currentState:revoked,detectedAt:'2026-07-16T01:00:00.000Z'})); assert.notEqual(authorityEventFingerprint({tokenId:'t',severity:3,previousState:active,currentState:revoked,detectedAt:'2026-07-16T00:00:00.000Z'}),authorityEventFingerprint({tokenId:'t',severity:3,previousState:revoked,currentState:active,detectedAt:'2026-07-16T00:00:00.000Z'})); });
test('holder concentration requires a previous numeric baseline and meaningful increase',()=>{ assert.equal(shouldEmitHolderConcentration(null,38.2),false); assert.equal(shouldEmitHolderConcentration(49,49),false); assert.equal(shouldEmitHolderConcentration(38.2,49),true); });
test('feed grouping filters real matching events and sorts by severity count recency',()=>{ const events=[{id:'1',tokenId:'a',mintAddress:'mintA',eventType:'holder_concentration_spike',severity:4,confidence:.9,summary:'holder',detectedAt:'2026-07-16T00:00:00.000Z'},{id:'2',tokenId:'a',mintAddress:'mintA',eventType:'holder_concentration_spike',severity:4,confidence:.9,summary:'holder2',detectedAt:'2026-07-16T01:00:00.000Z'},{id:'3',tokenId:'b',mintAddress:'mintB',eventType:'authority_change',severity:5,confidence:.99,summary:'auth',detectedAt:'2026-07-15T00:00:00.000Z'}]; const all=groupEventsByToken(events,'all'); assert.deepEqual(all.map(g=>g.mintAddress),['mintB','mintA']); assert.equal(all[1].count,2); assert.equal(groupEventsByToken(events,'holders').length,1); assert.equal(groupEventsByToken([],'all').length,0); });
