import test from 'node:test';
import assert from 'node:assert/strict';
import { createPhase2Repository } from '../lib/server/phase2/repository-core.mjs';
const MINT='11111111111111111111111111111111';
const normalizeMint=(v)=>typeof v==='string'&&/^[1-9A-HJ-NP-Za-km-z]{32,44}$/.test(v.trim())?v.trim():null;
function db(){return {tokens:[{id:'token-a',mint_address:MINT,name:'Token',symbol:'TOK',logo_url:null}],risk_reports:[{id:'risk-1',token_id:'token-a',overall_risk_score:42,overall_risk_label:'Medium',confidence:100,risk_factors:{factors:[{category:'holders'}],confidence:100},ai_headline:'Headline',ai_summary:'Summary',ai_findings:['Finding'],ai_limitations:['Limitation'],ai_provider:'groq',ai_model:'m',ai_generated_at:'2026-07-16T00:00:00.000Z',generated_at:'2026-07-16T00:00:00.000Z',calculated_at:null}],token_snapshots:[{id:'snap-1',token_id:'token-a',source:'unit',snapshot_at:'2026-07-16T00:00:00.000Z'}],saved_analyses:[],watchlist_items:[]}}
function client(state){let id=1; class Q{constructor(table){this.table=table;this.filters=[];this._order=[];this._limit=null;this._range=null;this.op='select';this.payload=null;this.opts=null;} select(_s,opts){this.opts=opts;return this;} eq(k,v){this.filters.push([k,v]);return this;} in(k,vs){this.filters.push([k,new Set(vs)]);return this;} order(k,o){this._order.push([k,o]);return this;} limit(n){this._limit=n;return this;} range(f,t){this._range=[f,t];return this;} insert(p){this.op='insert';this.payload=p;return this;} upsert(p){this.op='upsert';this.payload=p;return this;} delete(){this.op='delete';return this;} rows(){let r=[...(state[this.table]??[])]; for(const [k,v] of this.filters) r=r.filter(x=>v instanceof Set?v.has(x[k]):x[k]===v); for(const [k,o] of this._order) r.sort((a,b)=>String(o?.ascending?a[k]:b[k]).localeCompare(String(o?.ascending?b[k]:a[k]))); if(this._range) r=r.slice(this._range[0],this._range[1]+1); if(this._limit!==null) r=r.slice(0,this._limit); return r;} async maybeSingle(){return {data:this.rows()[0]??null,error:null};} async single(){if(this.op==='insert'){if(this.table==='saved_analyses'&&this.payload.idempotency_key&&state.saved_analyses.some(r=>r.user_id===this.payload.user_id&&r.idempotency_key===this.payload.idempotency_key)) return {data:null,error:{code:'23505'}}; const row={id:`${this.table}-${id++}`,created_at:new Date().toISOString(),...this.payload}; state[this.table].push(row); return {data:row,error:null};} if(this.op==='upsert'){let row=state[this.table].find(r=>r.user_id===this.payload.user_id&&r.mint_address===this.payload.mint_address); if(!row){row={id:`${this.table}-${id++}`,created_at:new Date().toISOString(),...this.payload}; state[this.table].push(row);} else Object.assign(row,this.payload); return {data:row,error:null};} return {data:this.rows()[0]??null,error:null};} then(resolve){if(this.op==='delete'){const before=state[this.table].length; const doomed=new Set(this.rows()); state[this.table]=state[this.table].filter(r=>!doomed.has(r)); return resolve({data:null,error:null,count:before-state[this.table].length});} const rows=this.rows(); return resolve({data:rows,error:null,count:this.opts?.count==='exact'?rows.length:null});}} return {from(t){return new Q(t)}}}
function repo(){const state=db(); return {state, repo:createPhase2Repository(client(state), normalizeMint)}}
test('malformed mint and pagination contract are bounded',()=>{ assert.equal(normalizeMint('bad-risk-score'), null); const limit=Math.min(50, Math.max(1, Number.parseInt('500',10)||20)); assert.equal(limit,50); });
test('owner can read and delete while another user cannot read or delete saved analysis',async()=>{const {state,repo:r}=repo(); const saved=await r.createSavedAnalysis('user-a',MINT,'idem-a'); assert.equal(await r.getSavedAnalysis('user-b',saved.id), null); await r.deleteSavedAnalysis('user-b',saved.id); assert.equal(state.saved_analyses.length,1); assert.equal((await r.getSavedAnalysis('user-a',saved.id)).id,saved.id); await r.deleteSavedAnalysis('user-a',saved.id); assert.equal(state.saved_analyses.length,0);});
test('authoritative values are inserted and saved snapshot is immutable after current report changes',async()=>{const {state,repo:r}=repo(); const saved=await r.createSavedAnalysis('user-a',MINT,'idem-b'); assert.equal(saved.risk_score,42); assert.equal(saved.confidence,100); state.risk_reports.unshift({...state.risk_reports[0],id:'risk-2',overall_risk_score:99,confidence:25,generated_at:'2026-07-17T00:00:00.000Z',ai_generated_at:'2026-07-17T00:00:00.000Z'}); const unchanged=await r.getSavedAnalysis('user-a',saved.id); assert.equal(unchanged.risk_score,42); assert.equal(unchanged.confidence,100);});
test('same idempotency key returns one saved record but same token can be saved later with a new key',async()=>{const {state,repo:r}=repo(); const a=await r.createSavedAnalysis('user-a',MINT,'same-key'); const b=await r.createSavedAnalysis('user-a',MINT,'same-key'); assert.equal(a.id,b.id); assert.equal(state.saved_analyses.length,1); const c=await r.createSavedAnalysis('user-a',MINT,'later-key'); assert.notEqual(c.id,a.id); assert.equal(state.saved_analyses.length,2);});
test('watchlist list and delete operations are scoped to the authenticated user',async()=>{const {state,repo:r}=repo(); await r.addWatchlistItem('user-a',MINT); await r.addWatchlistItem('user-b',MINT); assert.equal((await r.listWatchlist('user-a')).length,1); await r.removeWatchlistItem('user-b',MINT); assert.equal((await r.listWatchlist('user-a')).length,1); assert.equal(state.watchlist_items.length,1);});
test('dashboard counts are user-scoped and current watchlist intelligence does not mutate saved snapshot',async()=>{const {state,repo:r}=repo(); const saved=await r.createSavedAnalysis('user-a',MINT,'dash-a'); await r.createSavedAnalysis('user-b',MINT,'dash-b'); await r.addWatchlistItem('user-a',MINT); state.risk_reports.unshift({...state.risk_reports[0],id:'risk-new',overall_risk_score:5,generated_at:'2026-07-18T00:00:00.000Z'}); const dash=await r.getDashboardData('user-a'); assert.equal(dash.counts.savedAnalyses,1); assert.equal(dash.counts.watchlist,1); assert.equal(dash.latestRisk.get('token-a').score,5); assert.equal((await r.getSavedAnalysis('user-a',saved.id)).risk_score,42);});
